//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EixemX.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EixemX.Localization.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de facturation.
        /// </summary>
        internal static string Account_Address_Title {
            get {
                return ResourceManager.GetString("Account_Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banque.
        /// </summary>
        internal static string Account_BankCard_FieldBank {
            get {
                return ResourceManager.GetString("Account_BankCard_FieldBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        internal static string Account_BankCard_FieldCardNumber {
            get {
                return ResourceManager.GetString("Account_BankCard_FieldCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire le.
        /// </summary>
        internal static string Account_BankCard_FieldDateExpire {
            get {
                return ResourceManager.GetString("Account_BankCard_FieldDateExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIB.
        /// </summary>
        internal static string Account_BankCard_FieldIban {
            get {
                return ResourceManager.GetString("Account_BankCard_FieldIban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte personnelle.
        /// </summary>
        internal static string Account_BankCard_IbanTitle {
            get {
                return ResourceManager.GetString("Account_BankCard_IbanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte bancaire.
        /// </summary>
        internal static string Account_BankCard_Title {
            get {
                return ResourceManager.GetString("Account_BankCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        internal static string Account_Field_Birthday {
            get {
                return ResourceManager.GetString("Account_Field_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse mail.
        /// </summary>
        internal static string Account_Field_Email {
            get {
                return ResourceManager.GetString("Account_Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string Account_Field_Firstname {
            get {
                return ResourceManager.GetString("Account_Field_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Account_Field_Lastname {
            get {
                return ResourceManager.GetString("Account_Field_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        internal static string Account_Field_Password {
            get {
                return ResourceManager.GetString("Account_Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenu mensuel.
        /// </summary>
        internal static string Account_Finance_Title {
            get {
                return ResourceManager.GetString("Account_Finance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        internal static string Account_Link_PasswordForget {
            get {
                return ResourceManager.GetString("Account_Link_PasswordForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MON PROFIL.
        /// </summary>
        internal static string Account_ProfileTitle {
            get {
                return ResourceManager.GetString("Account_ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier vos identifiants.
        /// </summary>
        internal static string Alert_Authentication_Credential {
            get {
                return ResourceManager.GetString("Alert_Authentication_Credential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérification des identifiants ....
        /// </summary>
        internal static string Alert_Authentication_InProgress {
            get {
                return ResourceManager.GetString("Alert_Authentication_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre connexion internet pour vous connecter.
        /// </summary>
        internal static string Alert_Authentication_Network {
            get {
                return ResourceManager.GetString("Alert_Authentication_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectez-vous avec le mot de passe reçu par mail.
        /// </summary>
        internal static string Alert_Authentication_PasswordEmailDone {
            get {
                return ResourceManager.GetString("Alert_Authentication_PasswordEmailDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un mail va vous être envoyé ....
        /// </summary>
        internal static string Alert_Authentication_PasswordEmailInProgress {
            get {
                return ResourceManager.GetString("Alert_Authentication_PasswordEmailInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous allez recevoir un mail vous permettant de réinitialiser votre mot de passe.
        /// </summary>
        internal static string Alert_Authentication_PasswordEmailSendMessage {
            get {
                return ResourceManager.GetString("Alert_Authentication_PasswordEmailSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié.
        /// </summary>
        internal static string Alert_Authentication_PasswordEmailSendTitle {
            get {
                return ResourceManager.GetString("Alert_Authentication_PasswordEmailSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez renseigner votre mail.
        /// </summary>
        internal static string Alert_Authentication_PasswordForgetEmail {
            get {
                return ResourceManager.GetString("Alert_Authentication_PasswordForgetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mail doit être celui associé à votre compte.
        /// </summary>
        internal static string Alert_Authentication_PasswordForgetEmailNotExist {
            get {
                return ResourceManager.GetString("Alert_Authentication_PasswordForgetEmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez renseigner le montant à emprunter.
        /// </summary>
        internal static string Alert_Borrow_MandatoryAmount {
            get {
                return ResourceManager.GetString("Alert_Borrow_MandatoryAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez renseigner votre mot de passe.
        /// </summary>
        internal static string Alert_Borrow_MandatoryPassword {
            get {
                return ResourceManager.GetString("Alert_Borrow_MandatoryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre mot de passe.
        /// </summary>
        internal static string Alert_Borrow_UnableToAuthenticate {
            get {
                return ResourceManager.GetString("Alert_Borrow_UnableToAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires access to remote data, but you don&apos;t seem to currently have a network connnection. Check your connection and try again..
        /// </summary>
        internal static string Alert_NetworkConnection_Message {
            get {
                return ResourceManager.GetString("Alert_NetworkConnection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non connecté.
        /// </summary>
        internal static string Alert_NetworkConnection_Title {
            get {
                return ResourceManager.GetString("Alert_NetworkConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre date de naissance.
        /// </summary>
        internal static string Alert_Registration_BirthdayInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_BirthdayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre adresse mail.
        /// </summary>
        internal static string Alert_Registration_EmainInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_EmainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre prénom.
        /// </summary>
        internal static string Alert_Registration_FirstnameInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_FirstnameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de votre compte en cours ....
        /// </summary>
        internal static string Alert_Registration_InProgress {
            get {
                return ResourceManager.GetString("Alert_Registration_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre nom.
        /// </summary>
        internal static string Alert_Registration_LastnameInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_LastnameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre mot de passe.
        /// </summary>
        internal static string Alert_Registration_PasswordInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez confirmer le même mot de passe.
        /// </summary>
        internal static string Alert_Registration_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Alert_Registration_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier vos informations.
        /// </summary>
        internal static string Alert_Registration_Retry {
            get {
                return ResourceManager.GetString("Alert_Registration_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIXEM.
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCHAIN REMBOURSEMENT.
        /// </summary>
        internal static string Borrow_NextRefound {
            get {
                return ResourceManager.GetString("Borrow_NextRefound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPACITÉ D&apos;EMPRUNT RESTANTE.
        /// </summary>
        internal static string Borrow_RemainingCapacity {
            get {
                return ResourceManager.GetString("Borrow_RemainingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPRUNTER.
        /// </summary>
        internal static string Borrow_Title {
            get {
                return ResourceManager.GetString("Borrow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant emprunté : {0} €.
        /// </summary>
        internal static string BorrowCreateConfirmAmount {
            get {
                return ResourceManager.GetString("BorrowCreateConfirmAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous disposez désormais de cette somme payable directement avec votre carte bleu..
        /// </summary>
        internal static string BorrowCreateConfirmInfoText1 {
            get {
                return ResourceManager.GetString("BorrowCreateConfirmInfoText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous vous rappelons que cette somme empruntée sera débitée le {0} du mois prochain..
        /// </summary>
        internal static string BorrowCreateConfirmInfoText2 {
            get {
                return ResourceManager.GetString("BorrowCreateConfirmInfoText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRMATION DE VOTRE EMPRUNT.
        /// </summary>
        internal static string BorrowCreateConfirmTitle {
            get {
                return ResourceManager.GetString("BorrowCreateConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacité d&apos;emprunt maximum :.
        /// </summary>
        internal static string BorrowCreateEnterAmout {
            get {
                return ResourceManager.GetString("BorrowCreateEnterAmout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} € .
        /// </summary>
        internal static string BorrowCreateEnterAmoutEuro {
            get {
                return ResourceManager.GetString("BorrowCreateEnterAmoutEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le montant désiré :.
        /// </summary>
        internal static string BorrowCreateEnterAmoutTitle {
            get {
                return ResourceManager.GetString("BorrowCreateEnterAmoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le transfert est en cours ....
        /// </summary>
        internal static string BorrowCreateFinalMessage {
            get {
                return ResourceManager.GetString("BorrowCreateFinalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les montants ne peuvent comporter de centimes.
        /// </summary>
        internal static string BorrowCreateNoCentimes {
            get {
                return ResourceManager.GetString("BorrowCreateNoCentimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDER VOTRE DEMANDE.
        /// </summary>
        internal static string BorrowCreateValidateAmount {
            get {
                return ResourceManager.GetString("BorrowCreateValidateAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant demandé : {0} €.
        /// </summary>
        internal static string BorrowCreateValidateAmountRequested {
            get {
                return ResourceManager.GetString("BorrowCreateValidateAmountRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre mot de passe :.
        /// </summary>
        internal static string BorrowCreateValidatePasswordEnterCode {
            get {
                return ResourceManager.GetString("BorrowCreateValidatePasswordEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        internal static string BorrowCreateValidatePasswordTitle {
            get {
                return ResourceManager.GetString("BorrowCreateValidatePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        internal static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        internal static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        internal static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        internal static string Button_Registration {
            get {
                return ResourceManager.GetString("Button_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        internal static string Button_SendPassword {
            get {
                return ResourceManager.GetString("Button_SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        internal static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        internal static string Button_Validate {
            get {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISPONIBLE.
        /// </summary>
        internal static string Dashboard_BorrowAvailable {
            get {
                return ResourceManager.GetString("Dashboard_BorrowAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jusqu&apos;au {0}.
        /// </summary>
        internal static string Dashboard_BorrowAvailableTo {
            get {
                return ResourceManager.GetString("Dashboard_BorrowAvailableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to détails.
        /// </summary>
        internal static string Dashboard_Details {
            get {
                return ResourceManager.GetString("Dashboard_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTÉRÊTS.
        /// </summary>
        internal static string Dashboard_Interest {
            get {
                return ResourceManager.GetString("Dashboard_Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIS À DISPOSITION.
        /// </summary>
        internal static string Dashboard_Loan {
            get {
                return ResourceManager.GetString("Dashboard_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir un montant.
        /// </summary>
        internal static string Emprunter_BorrowButton {
            get {
                return ResourceManager.GetString("Emprunter_BorrowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} €.
        /// </summary>
        internal static string Field_PriceEuro {
            get {
                return ResourceManager.GetString("Field_PriceEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Menu_Dashboard {
            get {
                return ResourceManager.GetString("Menu_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emprunter.
        /// </summary>
        internal static string Menu_Emprunter {
            get {
                return ResourceManager.GetString("Menu_Emprunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historiques.
        /// </summary>
        internal static string Menu_History {
            get {
                return ResourceManager.GetString("Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        internal static string Menu_Payer {
            get {
                return ResourceManager.GetString("Menu_Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêter.
        /// </summary>
        internal static string Menu_Preter {
            get {
                return ResourceManager.GetString("Menu_Preter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionnels.
        /// </summary>
        internal static string Menu_Professional {
            get {
                return ResourceManager.GetString("Menu_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirer.
        /// </summary>
        internal static string Menu_Retirer {
            get {
                return ResourceManager.GetString("Menu_Retirer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre mail :.
        /// </summary>
        internal static string PasswordForget_EnterEmail {
            get {
                return ResourceManager.GetString("PasswordForget_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOT DE PASSE OUBLIÉ.
        /// </summary>
        internal static string PasswordForget_Title {
            get {
                return ResourceManager.GetString("PasswordForget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation du mot de passe.
        /// </summary>
        internal static string Registration_ConfirmSecret {
            get {
                return ResourceManager.GetString("Registration_ConfirmSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisie du mot de passe.
        /// </summary>
        internal static string Registration_PasswordTitle {
            get {
                return ResourceManager.GetString("Registration_PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code secret.
        /// </summary>
        internal static string Registration_Secret {
            get {
                return ResourceManager.GetString("Registration_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSCRIPTION.
        /// </summary>
        internal static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        internal static string Registration_TitleBar {
            get {
                return ResourceManager.GetString("Registration_TitleBar", resourceCulture);
            }
        }
    }
}
