//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EixemX.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EixemX.Localization.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance.
        /// </summary>
        internal static string Account_Field_Birthday {
            get {
                return ResourceManager.GetString("Account_Field_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse mail.
        /// </summary>
        internal static string Account_Field_Email {
            get {
                return ResourceManager.GetString("Account_Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string Account_Field_Firstname {
            get {
                return ResourceManager.GetString("Account_Field_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Account_Field_Lastname {
            get {
                return ResourceManager.GetString("Account_Field_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        internal static string Account_Field_Password {
            get {
                return ResourceManager.GetString("Account_Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        internal static string Account_Link_PasswordForget {
            get {
                return ResourceManager.GetString("Account_Link_PasswordForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier vos identifiants.
        /// </summary>
        internal static string Alert_Authentication_Credential {
            get {
                return ResourceManager.GetString("Alert_Authentication_Credential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion en cours ....
        /// </summary>
        internal static string Alert_Authentication_InProgress {
            get {
                return ResourceManager.GetString("Alert_Authentication_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre connexion internet pour vous connecter.
        /// </summary>
        internal static string Alert_Authentication_Network {
            get {
                return ResourceManager.GetString("Alert_Authentication_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires access to remote data, but you don&apos;t seem to currently have a network connnection. Check your connection and try again..
        /// </summary>
        internal static string Alert_NetworkConnection_Message {
            get {
                return ResourceManager.GetString("Alert_NetworkConnection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non connecté.
        /// </summary>
        internal static string Alert_NetworkConnection_Title {
            get {
                return ResourceManager.GetString("Alert_NetworkConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre date de naissance.
        /// </summary>
        internal static string Alert_Registration_BirthdayInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_BirthdayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre adresse mail.
        /// </summary>
        internal static string Alert_Registration_EmainInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_EmainInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre prénom.
        /// </summary>
        internal static string Alert_Registration_FirstnameInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_FirstnameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de votre compte en cours ....
        /// </summary>
        internal static string Alert_Registration_InProgress {
            get {
                return ResourceManager.GetString("Alert_Registration_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre nom.
        /// </summary>
        internal static string Alert_Registration_LastnameInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_LastnameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier votre mot de passe.
        /// </summary>
        internal static string Alert_Registration_PasswordInvalid {
            get {
                return ResourceManager.GetString("Alert_Registration_PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez confirmer le même mot de passe.
        /// </summary>
        internal static string Alert_Registration_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Alert_Registration_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier vos informations.
        /// </summary>
        internal static string Alert_Registration_Retry {
            get {
                return ResourceManager.GetString("Alert_Registration_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        internal static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        internal static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        internal static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        internal static string Button_Registration {
            get {
                return ResourceManager.GetString("Button_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        internal static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation du mot de passe.
        /// </summary>
        internal static string Registration_ConfirmSecret {
            get {
                return ResourceManager.GetString("Registration_ConfirmSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisie du mot de passe.
        /// </summary>
        internal static string Registration_PasswordTitle {
            get {
                return ResourceManager.GetString("Registration_PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code secret.
        /// </summary>
        internal static string Registration_Secret {
            get {
                return ResourceManager.GetString("Registration_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSCRIPTION.
        /// </summary>
        internal static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        internal static string Registration_TitleBar {
            get {
                return ResourceManager.GetString("Registration_TitleBar", resourceCulture);
            }
        }
    }
}
